stages:
  - build
#   - test
  - deploy

build website:
  stage: build
  image: node:19
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build  
  only:
    - release

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 sync build/ s3://$S3_BUCKET --delete
  only:
    - release

# clear s3 cache:
#   stage: deploy
#   image: 
#     name: amazon/aws-cli
#     entrypoint: [""]
#   script:
#     - aws --version
#     # clear cloudfront cache to instantly show changes
#   only:
#     - release


